Repository gotk3/gotk3, pull requests merged in 2020-02, with the labels that each got.

#504 Tree model sort
  gtk/gtk.go
  gtk/gtk.go.h
Labels: help wanted, work in progress

#510 Abstraction of GtkTreeSortable
  gtk/gtk.go
  gtk/gtk.go.h
Labels: help wanted, work in progress

#517 Add gtk_deprecated build tag
  README.md
  gdk/gdk_deprecated_since_3_10.go
  gdk/gdk_deprecated_since_3_16.go
  gdk/gdk_deprecated_since_3_20.go
  gdk/gdk_deprecated_since_3_22.go
  gtk/gtk_deprecated_since_3_10.go
  gtk/gtk_deprecated_since_3_12.go
  gtk/gtk_deprecated_since_3_14.go
  gtk/gtk_deprecated_since_3_16.go
  gtk/gtk_deprecated_since_3_18.go
  gtk/gtk_deprecated_since_3_20.go
  gtk/gtk_deprecated_since_3_22.go
  gtk/gtk_deprecated_since_3_24.go
  gtk/gtk_deprecated_since_3_8.go
  gtk/testing_deprecated_since_3_20.go
Labels: documentation

#518 GVariant and GMenu bindings step 1 (breaking changes)
  glib/gvariant.go
  glib/gvariant_test.go
  glib/gvarianttype.go
  glib/gvarianttype_test.go
  glib/menu.go
  glib/menu_test.go
Labels: breaking changes

#521 Clean up cgo callbacks
  gtk/gtk.go
  gtk/gtk_export.go
  gtk/gtk_export_since_3_10.go
  gtk/gtk_export_since_3_14.go
  gtk/gtk_since_3_10.go
  gtk/gtk_since_3_12.go
  gtk/gtk_since_3_14.go
  gtk/gtk_since_3_20.go
  gtk/gtk_since_3_8.go
  gtk/print.go
  gtk/print_test.go
  gtk/widget_export_since_3_8.go
  gtk/widget_since_3_8.go
Labels: breaking changes, enhancement
